// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { context } from "$live/live.ts";
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";

import * as $$$0 from "./sections/Links.tsx";
import * as $$$1 from "deco-sites/std/sections/SEO.tsx";
import * as $$$2 from "deco-sites/std/sections/SEOPDP.tsx";
import * as $$$3 from "deco-sites/std/sections/SEOPLP.tsx";
import * as $$$4 from "deco-sites/std/sections/configOCC.global.tsx";
import * as $$$5 from "deco-sites/std/sections/configShopify.global.tsx";
import * as $$$6 from "deco-sites/std/sections/configVTEX.global.tsx";
import * as $$$7 from "deco-sites/std/sections/configYourViews.tsx";
import * as $$$$0 from "$live/functions/EffectSelectPage.ts";
import * as $$$$1 from "$live/functions/MatchDate.ts";
import * as $$$$2 from "$live/functions/MatchEnvironment.ts";
import * as $$$$3 from "$live/functions/MatchRandom.ts";
import * as $$$$4 from "$live/functions/MatchSite.ts";
import * as $$$$5 from "$live/functions/MatchUserAgent.ts";
import * as $$$$6 from "deco-sites/std/functions/occProductDetailsPage.ts";
import * as $$$$7 from "deco-sites/std/functions/shopifyProductDetailsPage.ts";
import * as $$$$8 from "deco-sites/std/functions/shopifyProductList.ts";
import * as $$$$9 from "deco-sites/std/functions/shopifyProductListingPage.ts";
import * as $$$$10 from "deco-sites/std/functions/vtexConfig.ts";
import * as $$$$11 from "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts";
import * as $$$$12 from "deco-sites/std/functions/vtexLegacyProductList.ts";
import * as $$$$13 from "deco-sites/std/functions/vtexLegacyProductListingPage.ts";
import * as $$$$14 from "deco-sites/std/functions/vtexNavbar.ts";
import * as $$$$15 from "deco-sites/std/functions/vtexProductDetailsPage.ts";
import * as $$$$16 from "deco-sites/std/functions/vtexProductList.ts";
import * as $$$$17 from "deco-sites/std/functions/vtexProductListingPage.ts";
import * as $$$$18 from "deco-sites/std/functions/vtexSuggestions.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {},
  sections: {
    "./sections/Links.tsx": $$$0,
    "deco-sites/std/sections/SEO.tsx": $$$1,
    "deco-sites/std/sections/SEOPDP.tsx": $$$2,
    "deco-sites/std/sections/SEOPLP.tsx": $$$3,
    "deco-sites/std/sections/configOCC.global.tsx": $$$4,
    "deco-sites/std/sections/configShopify.global.tsx": $$$5,
    "deco-sites/std/sections/configVTEX.global.tsx": $$$6,
    "deco-sites/std/sections/configYourViews.tsx": $$$7,
  },
  functions: {
    "$live/functions/EffectSelectPage.ts": $$$$0,
    "$live/functions/MatchDate.ts": $$$$1,
    "$live/functions/MatchEnvironment.ts": $$$$2,
    "$live/functions/MatchRandom.ts": $$$$3,
    "$live/functions/MatchSite.ts": $$$$4,
    "$live/functions/MatchUserAgent.ts": $$$$5,
    "deco-sites/std/functions/occProductDetailsPage.ts": $$$$6,
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": $$$$7,
    "deco-sites/std/functions/shopifyProductList.ts": $$$$8,
    "deco-sites/std/functions/shopifyProductListingPage.ts": $$$$9,
    "deco-sites/std/functions/vtexConfig.ts": $$$$10,
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": $$$$11,
    "deco-sites/std/functions/vtexLegacyProductList.ts": $$$$12,
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": $$$$13,
    "deco-sites/std/functions/vtexNavbar.ts": $$$$14,
    "deco-sites/std/functions/vtexProductDetailsPage.ts": $$$$15,
    "deco-sites/std/functions/vtexProductList.ts": $$$$16,
    "deco-sites/std/functions/vtexProductListingPage.ts": $$$$17,
    "deco-sites/std/functions/vtexSuggestions.ts": $$$$18,
  },
  schemas: {
    "./sections/Links.tsx": {
      "inputSchema": {
        "title": " Links",
        "type": "object",
        "properties": {
          "header": {
            "title": "Header",
            "type": "object",
            "properties": {
              "title": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Title",
              },
              "description": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Description",
              },
              "logo": {
                "format": "image-uri",
                "type": "string",
                "title": "Logo",
              },
              "textColor": {
                "type": [
                  "string",
                  "null",
                ],
                "title": "Text Color",
              },
            },
            "required": [],
          },
          "links": {
            "title": "Links",
            "type": "object",
            "properties": {
              "items": {
                "type": "array",
                "items": {
                  "title": "Link",
                  "type": "object",
                  "properties": {
                    "icon": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "ChevronLeft",
                        },
                        {
                          "type": "string",
                          "const": "ChevronRight",
                        },
                        {
                          "type": "string",
                          "const": "ChevronUp",
                        },
                        {
                          "type": "string",
                          "const": "ChevronDown",
                        },
                        {
                          "type": "string",
                          "const": "QuestionMarkCircle",
                        },
                        {
                          "type": "string",
                          "const": "User",
                        },
                        {
                          "type": "string",
                          "const": "ShoppingCart",
                        },
                        {
                          "type": "string",
                          "const": "Bars3",
                        },
                        {
                          "type": "string",
                          "const": "Heart",
                        },
                        {
                          "type": "string",
                          "const": "MagnifyingGlass",
                        },
                        {
                          "type": "string",
                          "const": "XMark",
                        },
                        {
                          "type": "string",
                          "const": "Plus",
                        },
                        {
                          "type": "string",
                          "const": "Minus",
                        },
                        {
                          "type": "string",
                          "const": "MapPin",
                        },
                        {
                          "type": "string",
                          "const": "Phone",
                        },
                        {
                          "type": "string",
                          "const": "Elo",
                        },
                        {
                          "type": "string",
                          "const": "Mastercard",
                        },
                        {
                          "type": "string",
                          "const": "Visa",
                        },
                        {
                          "type": "string",
                          "const": "Pix",
                        },
                        {
                          "type": "string",
                          "const": "Logo",
                        },
                        {
                          "type": "string",
                          "const": "Facebook",
                        },
                        {
                          "type": "string",
                          "const": "Instagram",
                        },
                        {
                          "type": "string",
                          "const": "Tiktok",
                        },
                        {
                          "type": "string",
                          "const": "Truck",
                        },
                        {
                          "type": "string",
                          "const": "Discount",
                        },
                        {
                          "type": "string",
                          "const": "Return",
                        },
                        {
                          "type": "string",
                          "const": "CreditCard",
                        },
                        {
                          "type": "string",
                          "const": "Deco",
                        },
                        {
                          "type": "string",
                          "const": "Discord",
                        },
                        {
                          "type": "string",
                          "const": "Trash",
                        },
                        {
                          "type": "string",
                          "const": "FilterList",
                        },
                        {
                          "type": "string",
                          "const": "WhatsApp",
                        },
                        {
                          "type": "string",
                          "const": "Linkedin",
                        },
                        {
                          "type": "string",
                          "const": "Share",
                        },
                      ],
                      "title": "Icon",
                      "description": "20px transparent png recommended",
                    },
                    "label": {
                      "type": "string",
                      "title": "Label",
                    },
                    "href": {
                      "type": "string",
                      "title": "Href",
                    },
                  },
                  "required": [
                    "label",
                    "href",
                  ],
                },
                "title": "Items",
              },
              "style": {
                "title": "Style",
                "type": "object",
                "properties": {
                  "textColor": {
                    "type": [
                      "string",
                      "null",
                    ],
                    "title": "Text Color",
                  },
                  "backgroundColors": {
                    "title": "Background Colors",
                    "type": "object",
                    "properties": {
                      "neutral": {
                        "type": "array",
                        "items": {
                          "type": "string",
                        },
                        "title": "Neutral",
                      },
                      "hover": {
                        "type": "array",
                        "items": {
                          "type": "string",
                        },
                        "title": "Hover",
                      },
                    },
                    "required": [],
                  },
                },
                "required": [],
              },
            },
            "required": [],
          },
          "social": {
            "title": "Social",
            "type": "object",
            "properties": {
              "items": {
                "type": "array",
                "items": {
                  "title": "Social",
                  "type": "object",
                  "properties": {
                    "href": {
                      "type": "string",
                      "title": "Href",
                    },
                    "label": {
                      "type": "string",
                      "anyOf": [
                        {
                          "type": "string",
                          "const": "Instagram",
                        },
                        {
                          "type": "string",
                          "const": "Facebook",
                        },
                        {
                          "type": "string",
                          "const": "Linkedin",
                        },
                        {
                          "type": "string",
                          "const": "WhatsApp",
                        },
                        {
                          "type": "string",
                          "const": "Discord",
                        },
                        {
                          "type": "string",
                          "const": "Tiktok",
                        },
                      ],
                      "title": "Label",
                    },
                  },
                  "required": [
                    "href",
                    "label",
                  ],
                },
                "title": "Items",
              },
              "style": {
                "title": "Style",
                "type": "object",
                "properties": {
                  "iconColor": {
                    "type": [
                      "string",
                      "null",
                    ],
                    "title": "Icon Color",
                  },
                },
                "required": [],
              },
            },
            "required": [],
          },
          "background": {
            "title": "Background",
            "type": "object",
            "properties": {
              "image": {
                "format": "image-uri",
                "type": "string",
                "title": "Image",
              },
              "backgroundColors": {
                "type": "array",
                "items": {
                  "type": "string",
                },
                "title": "Background Colors",
              },
            },
            "required": [],
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "$live/functions/EffectSelectPage.ts": {
      "inputSchema": {
        "title": " Effect Select Page",
        "type": "object",
        "properties": {
          "pageIds": {
            "type": "array",
            "items": {
              "type": "number",
            },
            "title": "Page Ids",
          },
        },
        "required": [
          "pageIds",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchDate.ts": {
      "inputSchema": {
        "title": " Match Date",
        "type": "object",
        "properties": {
          "start": {
            "type": [
              "string",
              "null",
            ],
            "title": "Start",
            "format": "date-time",
          },
          "end": {
            "type": [
              "string",
              "null",
            ],
            "title": "End",
            "format": "date-time",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchEnvironment.ts": {
      "inputSchema": {
        "title": " Match Environment",
        "type": "object",
        "properties": {
          "environment": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "production",
              },
              {
                "type": "string",
                "const": "development",
              },
            ],
            "title": "Environment",
          },
        },
        "required": [
          "environment",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchRandom.ts": {
      "inputSchema": {
        "title": " Match Random",
        "type": "object",
        "properties": {
          "traffic": {
            "type": "number",
            "title": "Traffic",
          },
          "session": {
            "type": "boolean",
            "title": "Session",
          },
        },
        "required": [
          "traffic",
          "session",
        ],
      },
      "outputSchema": null,
    },
    "$live/functions/MatchSite.ts": {
      "inputSchema": {
        "title": " Match Site",
        "type": "object",
        "properties": {
          "siteId": {
            "type": "number",
            "title": "Site Id",
          },
        },
        "required": [
          "siteId",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "$live/functions/MatchUserAgent.ts": {
      "inputSchema": {
        "title": " Match User Agent",
        "type": "object",
        "properties": {
          "includes": {
            "type": [
              "string",
              "null",
            ],
            "title": "Includes",
          },
          "match": {
            "type": [
              "string",
              "null",
            ],
            "title": "Match",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "c995d72dc372b1b50bf9f70943e37fc94e1ccac9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/sections/SEO.tsx": {
      "inputSchema": {
        "title": " S E O",
        "type": "object",
        "properties": {
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPDP.tsx": {
      "inputSchema": {
        "title": " S E O P D P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "titleTemplate": {
            "type": "string",
            "title": "Title template",
            "description":
              "add a %s whenever you want it to be replaced with the product name",
            "default": "%s | Fashion Store",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Meta tag description",
            "description":
              "If not set, the product description will be used instead",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
          "titleTemplate",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/SEOPLP.tsx": {
      "inputSchema": {
        "title": " S E O P L P",
        "type": "object",
        "properties": {
          "page": {
            "$id": "dc324bcbdc313fdca3eaf23a9c1547d4702ee1ce",
            "format": "live-function",
            "type": "string",
            "title": "Page",
          },
          "title": {
            "type": [
              "string",
              "null",
            ],
            "title": "Title",
          },
          "description": {
            "type": [
              "string",
              "null",
            ],
            "title": "Description",
          },
          "url": {
            "type": [
              "string",
              "null",
            ],
            "title": "Url",
          },
          "imageUrl": {
            "type": [
              "string",
              "null",
            ],
            "title": "Image Url",
          },
          "themeColor": {
            "type": [
              "string",
              "null",
            ],
            "title": "Theme Color",
          },
        },
        "required": [
          "page",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configOCC.global.tsx": {
      "inputSchema": {
        "title": "Config O C C.global",
        "type": "object",
        "properties": {
          "baseUrl": {
            "type": "string",
            "title": "Base Url",
          },
          "nrpp": {
            "type": [
              "string",
              "null",
            ],
            "title": "Nrpp",
          },
        },
        "required": [
          "baseUrl",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configShopify.global.tsx": {
      "inputSchema": {
        "title": "Config Shopify.global",
        "type": "object",
        "properties": {
          "storeName": {
            "type": "string",
            "title": "Store Name",
            "description": "Shopify store name.",
          },
          "storefrontAccessToken": {
            "type": "string",
            "title": "Storefront Access Token",
            "description": "Shopify storefront access token.",
          },
        },
        "required": [
          "storeName",
          "storefrontAccessToken",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configVTEX.global.tsx": {
      "inputSchema": {
        "title": "Config V T E X.global",
        "type": "object",
        "properties": {
          "account": {
            "type": "string",
            "title": "Account",
            "description":
              "VTEX Account name. For more info, read here: https://help.vtex.com/en/tutorial/o-que-e-account-name--i0mIGLcg3QyEy8OCicEoC.",
          },
          "defaultLocale": {
            "type": "string",
            "title": "Default Locale",
            "description": "Locale used for VTEX Intelligent Search client.",
          },
          "defaultPriceCurrency": {
            "type": "string",
            "title": "Default Price Currency",
            "description": "Default price currency.",
            "default": "USD",
          },
          "defaultSalesChannel": {
            "type": "string",
            "title": "Default Sales Channel",
            "description":
              "VTEX sales channel. This will be the default sales channel your site. For more info, read here: https://help.vtex.com/tutorial/how-trade-policies-work--6Xef8PZiFm40kg2STrMkMV",
          },
          "defaultRegionId": {
            "type": [
              "string",
              "null",
            ],
            "title": "Default Region Id",
          },
          "defaultHideUnnavailableItems": {
            "type": [
              "boolean",
              "null",
            ],
            "title": "Default Hide Unnavailable Items",
          },
        },
        "required": [
          "account",
          "defaultLocale",
          "defaultPriceCurrency",
          "defaultSalesChannel",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/sections/configYourViews.tsx": {
      "inputSchema": {
        "title": "Config Your Views",
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "title": "Token",
          },
          "appId": {
            "type": "string",
            "title": "App Id",
          },
        },
        "required": [
          "token",
          "appId",
        ],
      },
      "outputSchema": null,
    },
    "deco-sites/std/functions/occProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Occ Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Shopify Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductList.ts": {
      "inputSchema": {
        "title": "Shopify Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "search term to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/shopifyProductListingPage.ts": {
      "inputSchema": {
        "title": "Shopify Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "dc324bcbdc313fdca3eaf23a9c1547d4702ee1ce",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexConfig.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Config",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "4a94f4ff0e8e4441f26651aaed22f0df82f38c93",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Legacy Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductList.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexLegacyProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Legacy Product Listing Page",
        "type": "object",
        "properties": {
          "term": {
            "type": [
              "string",
              "null",
            ],
            "title": "Term",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
          "ft": {
            "type": [
              "string",
              "null",
            ],
            "title": "Ft",
            "description": "FullText term",
          },
          "fq": {
            "type": [
              "string",
              "null",
            ],
            "title": "Fq",
          },
          "map": {
            "type": [
              "string",
              "null",
            ],
            "title": "Map",
            "description": "map param",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "dc324bcbdc313fdca3eaf23a9c1547d4702ee1ce",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexNavbar.ts": {
      "inputSchema": {
        "title": "Vtex Navbar",
        "type": "object",
        "properties": {
          "levels": {
            "type": [
              "number",
              "null",
            ],
            "title": "Levels",
            "description": "Number of levels of categories to be returned",
            "default": "2",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "0244534df7e3d23a94046f4c6f7086c2b72853b8",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductDetailsPage.ts": {
      "inputSchema": {
        "type": "null",
        "title": "Vtex Product Details Page",
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bf6c5311c35f44b8ba333ce3c2acd5fed0d8ad8a",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductList.ts": {
      "inputSchema": {
        "title": "Vtex Product List",
        "type": "object",
        "properties": {
          "query": {
            "type": "string",
            "title": "Query",
            "description": "query to use on search",
          },
          "count": {
            "type": "number",
            "title": "Count",
            "description": "total number of items to display",
          },
          "sort": {
            "type": "string",
            "anyOf": [
              {
                "type": "string",
                "const": "",
              },
              {
                "type": "string",
                "const": "price:desc",
              },
              {
                "type": "string",
                "const": "price:asc",
              },
              {
                "type": "string",
                "const": "orders:desc",
              },
              {
                "type": "string",
                "const": "name:desc",
              },
              {
                "type": "string",
                "const": "name:asc",
              },
              {
                "type": "string",
                "const": "release:desc",
              },
              {
                "type": "string",
                "const": "discount:desc",
              },
            ],
            "title": "Sort",
            "description": "search sort parameter",
          },
          "collection": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Collection",
            "description":
              "Collection ID or (Product Cluster id). For more info: https://developers.vtex.com/docs/api-reference/search-api#get-/api/catalog_system/pub/products/search .",
            "pattern": "\\d*",
          },
        },
        "required": [
          "query",
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "bae848f3957be1cb6ed2c2ac3847787272389ee9",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexProductListingPage.ts": {
      "inputSchema": {
        "title": "Vtex Product Listing Page",
        "type": "object",
        "properties": {
          "query": {
            "type": [
              "string",
              "null",
            ],
            "title": "Query",
            "description": "overides the query term",
          },
          "count": {
            "type": "number",
            "title": "Items per page",
            "description": "number of products per page to display",
          },
        },
        "required": [
          "count",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "dc324bcbdc313fdca3eaf23a9c1547d4702ee1ce",
          },
        },
        "additionalProperties": true,
      },
    },
    "deco-sites/std/functions/vtexSuggestions.ts": {
      "inputSchema": {
        "title": "Vtex Suggestions",
        "type": "object",
        "properties": {
          "count": {
            "type": [
              "number",
              "null",
            ],
            "title": "Count",
            "description": "limit the number of searches",
            "default": "4",
          },
        },
        "required": [],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "fa622ecbfb24e1b878a945d22f51f46a3e939525",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
context.manifest = manifest;

export default manifest;
